# Generated by Django 2.1.8 on 2019-06-01 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('persona', '0001_initial'),
        ('relacion', '0002_auto_20190531_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Persona')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.Producto')),
                ('tipo_relacion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relacion.Relacion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
