# Generated by Django 2.1.8 on 2019-07-19 00:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('numero_dni', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DetailFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('precio_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Client')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('numero_dni', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='fact',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Vendor'),
        ),
        migrations.AddField(
            model_name='detailfact',
            name='fact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Fact'),
        ),
        migrations.AddField(
            model_name='detailfact',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Product'),
        ),
    ]
